"""Initial schema

Revision ID: 2bb492188d4f
Revises: 
Create Date: 2025-07-26 14:44:22.819722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb492188d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_status', 'alert_logs', ['status'], unique=False)
    op.create_index('idx_alert_type_date', 'alert_logs', ['alert_type', 'created_at'], unique=False)
    op.create_table('data_source_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_source_date', 'data_source_logs', ['data_source', 'created_at'], unique=False)
    op.create_index('idx_log_status', 'data_source_logs', ['status'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stocks_symbol_active', 'stocks', ['symbol', 'is_active'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('option_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('call_volume', sa.Integer(), nullable=True),
    sa.Column('call_volume_baseline', sa.Float(), nullable=True),
    sa.Column('call_volume_ratio', sa.Float(), nullable=True),
    sa.Column('call_volume_trigger', sa.Boolean(), nullable=True),
    sa.Column('put_volume', sa.Integer(), nullable=True),
    sa.Column('put_volume_baseline', sa.Float(), nullable=True),
    sa.Column('put_volume_ratio', sa.Float(), nullable=True),
    sa.Column('put_volume_trigger', sa.Boolean(), nullable=True),
    sa.Column('short_term_call_volume', sa.Integer(), nullable=True),
    sa.Column('short_term_call_baseline', sa.Float(), nullable=True),
    sa.Column('short_term_call_ratio', sa.Float(), nullable=True),
    sa.Column('short_term_call_trigger', sa.Boolean(), nullable=True),
    sa.Column('otm_call_volume', sa.Integer(), nullable=True),
    sa.Column('otm_call_baseline', sa.Float(), nullable=True),
    sa.Column('otm_call_ratio', sa.Float(), nullable=True),
    sa.Column('otm_call_trigger', sa.Boolean(), nullable=True),
    sa.Column('call_oi_delta', sa.Integer(), nullable=True),
    sa.Column('call_oi_baseline', sa.Float(), nullable=True),
    sa.Column('call_oi_ratio', sa.Float(), nullable=True),
    sa.Column('call_oi_trigger', sa.Boolean(), nullable=True),
    sa.Column('unusual_activity_score', sa.Float(), nullable=True),
    sa.Column('insider_probability', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'snapshot_date', name='uq_anomaly_stock_date')
    )
    op.create_index('idx_anomaly_date', 'option_anomalies', ['snapshot_date'], unique=False)
    op.create_index('idx_anomaly_triggers', 'option_anomalies', ['call_volume_trigger', 'put_volume_trigger', 'short_term_call_trigger'], unique=False)
    op.create_table('option_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('contract_symbol', sa.String(length=50), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('bid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_symbol', 'snapshot_date', name='uq_option_contract_date')
    )
    op.create_index('idx_option_data_expiration', 'option_data', ['expiration'], unique=False)
    op.create_index('idx_option_data_stock_date', 'option_data', ['stock_id', 'snapshot_date'], unique=False)
    op.create_index('idx_option_data_type', 'option_data', ['option_type'], unique=False)
    op.create_table('stock_price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'snapshot_date', name='uq_stock_price_date')
    )
    op.create_index('idx_price_snapshot_date', 'stock_price_snapshots', ['snapshot_date'], unique=False)
    op.create_index('idx_price_snapshot_stock_date', 'stock_price_snapshots', ['stock_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_snapshot_stock_date', table_name='stock_price_snapshots')
    op.drop_index('idx_price_snapshot_date', table_name='stock_price_snapshots')
    op.drop_table('stock_price_snapshots')
    op.drop_index('idx_option_data_type', table_name='option_data')
    op.drop_index('idx_option_data_stock_date', table_name='option_data')
    op.drop_index('idx_option_data_expiration', table_name='option_data')
    op.drop_table('option_data')
    op.drop_index('idx_anomaly_triggers', table_name='option_anomalies')
    op.drop_index('idx_anomaly_date', table_name='option_anomalies')
    op.drop_table('option_anomalies')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index('idx_stocks_symbol_active', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('idx_log_status', table_name='data_source_logs')
    op.drop_index('idx_log_source_date', table_name='data_source_logs')
    op.drop_table('data_source_logs')
    op.drop_index('idx_alert_type_date', table_name='alert_logs')
    op.drop_index('idx_alert_status', table_name='alert_logs')
    op.drop_table('alert_logs')
    # ### end Alembic commands ### 