name: Daily Options Analysis

on:
  schedule:
    # Run Monday-Friday at 4:30 PM EST (after market close at 4:00 PM)
    - cron: '30 21 * * 1-5'
  workflow_dispatch:  # Allow manual triggers

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run options analysis
      env:
        SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        QUANDL_API_KEY: ${{ secrets.QUANDL_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        cd migrations
        python -m alembic upgrade head
        cd ..
        python runner.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: analysis-results
        path: logs/
        retention-days: 7 